### ISSUE TITLE
Health is on top of the second hotbar 

### ISSUE THREAD

**Issue by Deykii** [sidezbros/double_hotbar#23] opened 2024-04-30 13:36 UTC
When using Double hotbar, health, hungeGolozhr and exp didn't lift up. 
![IMG_20240430_183617](https://github.com/sidezbros/double_hotbar/assets/168557091/89ef2daf-303b-4f39-8e2d-33d6a14ae37a)

**Comment by Deykii** [comment] 2024-04-30 13:37
Oh, forgot. And also, item names have that problem too

**Comment by sidezbros** [comment] 2024-04-30 13:50
Double hotbar version, modloader and game version? This is a bug a found in earlier releases of the forge version of the mod. It should be resolved in the latest versions.

**Comment by Deykii** [comment] 2024-04-30 15:19
> Double hotbar version, modloader, and game version? This is a bug a found in earlier releases of the forge version of the mod. It should be resolved in the latest versions.

Version: 1.3.1-1.20.1
Modloader: Fabric
Game version: 1.20.1

**Comment by Deykii** [comment] 2024-05-06 18:13
I tried to use Double Hotbar 1.3.2.1, fabric version. There is still that problem....

**Comment by sidezbros** [comment] 2024-05-06 21:41
Are you using any other mods? When I initially saw this issue it reminded me of a forge issue I had recently but that was taking place in creative mode, so this is not the same bug. If you are in survival mode with default double hotbar settings and no other mods it should work right out of the box. Please try running with just double hotbar, fabric api, and cloth config installed with a new .minecraft folder. If the bug still persists then we can discuss what else it could be but between me and all play testers I've spoken with no one has had any issues with the status bars not moving in survival mode. If that is the case please reply with the version of the fabric loader, fabric api, cloth config, and double hotbar version so I can attempt to recreate the issue.

**Comment by EmptyDreams** [comment] 2024-06-09 15:21
> Are you using any other mods? When I initially saw this issue it reminded me of a forge issue I had recently but that was taking place in creative mode, so this is not the same bug. If you are in survival mode with default double hotbar settings and no other mods it should work right out of the box. Please try running with just double hotbar, fabric api, and cloth config installed with a new .minecraft folder. If the bug still persists then we can discuss what else it could be but between me and all play testers I've spoken with no one has had any issues with the status bars not moving in survival mode. If that is the case please reply with the version of the fabric loader, fabric api, cloth config, and double hotbar version so I can attempt to recreate the issue.

I also encountered the same problem, as shown below:

![image](https://github.com/sidezbros/double_hotbar/assets/44894906/0eb128b3-e9d0-4730-8391-85c2adc5e568)

I tried to get the module to stop displaying the second line to fix the problem, but there was also a problem:

![image](https://github.com/sidezbros/double_hotbar/assets/44894906/c6fd3f9f-35a0-4e85-807f-db4c8e6ad863)

It is worth noting that when I enable the display second line shortcut bar, sometimes all the ICONS are in the correct position, and sometimes the problems I mentioned above occur.

I really like the functionality of this module and hope to be able to fix this issue in the future!

**Comment by EmptyDreams** [comment] 2024-06-09 15:39
New discovery! After disabling the display of the second row of hotbars and restarting the game, the display appears to have returned to normal.

**Comment by sidezbros** [comment] 2024-06-20 20:40
I have yet again tested with a clean installation using just double hotbar 1.3.1 for 1.20.1, fabric api, cloth config, and mod menu. I experienced no issues. Even changing double hotbar settings I could not reproduce this bug. I believe this is likely a compatibility issue with one of the other mods listed above. I am marking this issue as resolved, but if someone can identify the problematic mod and provide me a list of steps to reproduce the error then I am happy to revisit the issue. Just create a new issue and list it as a compatibility problem instead of a general bug with the mod.

**Closed by sidezbros** 2024-06-20 20:40 UTC
